### ISSUE TITLE
QuPath pixel width and height does not change image size

### ISSUE THREAD

**Issue by FKiffer** [BIOP/ijp-imagetoatlas#103]
Following the documentation, I created a new QuPath project (Bio-Formats, non-triangulated), specifying the correct pixel-length representation (about 1um per pixel) and saved the project.

When importing the project into ABBA, the section shows up at over 10x the intended magnification. Is this related to my files? (each section is ~125MB, uint8, and 7530x5769px) or is this a bug?

I have tried altering the pixel sizes, saving and the project, and then restarting ABBA and re-importing the project, and it does not work, suggesting that editing the pixel width and height is not changing the image size or not working properly in QuPath.

A time-consuming workaround is to edit->interactive transform->scale x and y over and over again.

**Comment by NicoKiaru** [comment]
Ok, in the next release, the QuPath values in microns will be taken into account. However the value changes should be done in QuPath before importing the project in ABBA

**Comment by NicoKiaru** [comment]
This is done but not yet released (probably in a few weeks)

**Comment by NicoKiaru** [comment]
TODO : Mention this in ABBA's documentation

**Comment by yrleftbrain** [comment]
Hi! Has this been resolved/ bug fixed and released? Thanks!

**Comment by NicoKiaru** [comment]
@yrleftbrain sorry for the late reply. Yes this bug has been fixed. You need to set the pixel size in QuPath BEFORE opening it in ABBA however.

**Comment by NicoKiaru** [comment]
I'm letting the issue opened because I need to specify this in the documentation

**Comment by NicoKiaru** [comment]
Done in https://github.com/BIOP/ijp-imagetoatlas/commit/a79e1d5d477770ce496473e899e5316c4e71f32a
