### ISSUE TITLE
when importing QuPath project, only integer axis integer inter-slice spacing are allowed

### ISSUE THREAD

**Issue by ludovicosilvestri** [BIOP/ijp-imagetoatlas#104]
OS: Windows 10 64bit.

If I write a floating inter-slice spacing (e.g. 0.02), the system approximate it to 0. I have tried to change the international policies of Windows to UK (formerly they were Italy), but the problem persists. The only workaround I found is to reduce the number of slices, using 1 slice every mm.

**Comment by NicoKiaru** [comment]
I'll push a fix... FYI it's just a display issue. If you type 0.02 and go on, even if the display shows 0, the spacing will be of 20 microns.

Thanks for opening this issue. I'll close it once I pushed the fix
