### ISSUE TITLE
Problems with new registrations

### ISSUE THREAD

**Issue by eddycava16** [BIOP/ijp-imagetoatlas#107]
Good afternoon, Nicolas
I wanted to share with you an issue I've encountered with ABBA. I divided it in steps to make it clearer.
I added two screenshots at the bottom to clarify.

1. I have a series of brain slices that are registered both with deepslice, affine and spline and the manual registration.
2. I decide I want to change the slice's position on the atlas so I select the slices and remove the registrations one at a time. (If i remove the spline i am also removing the manual reg.?)
3. I drag the slices to their new, more correct position on the atlas.
4. A) I do all the registrations (affine/spline/manual) for the slices in their new position. I save and then when I load I notice the slices are in the new position on the atlas but now have four green registration icons under them and the images are completely distorted.
    B) After step A happened, I decided to save the project with the slices on the new position without the new registrations. In this case when I load the project my slices are in the new position on the atlas, but their image is distorted and they have two green registration icons under them. 
I would like to know if there is something I am doing wrong
Best Regards,
Edoardo

<img width="303" alt="ABBA- before save state" src="https://user-images.githubusercontent.com/22595641/140610695-babee64d-c18c-4058-856d-81c295724789.png">
<img width="299" alt="ABBA- after save state" src="https://user-images.githubusercontent.com/22595641/140610703-a300a352-e997-41fc-8651-f551c211e3bf.png">

**Comment by NicoKiaru** [comment]
Thanks for the detailed instructions, I'll try to reproduce it. I guess for some reasons the registrations have not really been removed

**Comment by NicoKiaru** [comment]
Solved in new version
