### ISSUE TITLE
Faster adjustment of Brightness & Contrast

### ISSUE THREAD

**Issue by Theresa-S** [BIOP/ijp-imagetoatlas#109]
I have more of a luxury request. When I import my images from a QuPath project, they all look like this:
![grafik](https://user-images.githubusercontent.com/61883896/141473429-0e6751ae-b588-4a34-beb7-870dc483c253.png)

This is because ABBA automatically sets the color range of all four channels of my 16-bit image from 0 - 255. So currently I have to manually click on every channel and type in the correct value range.
In order to make life easier, it would be awesome to have either an auto-adjustment of brightness/ contrast or a faster way to set all channels. In my case, 500 - 5000 works for all images, so being able to manipulate all channels at once would already be a huge help. 

Thank you for your awesome work! :-)

**Comment by NicoKiaru** [comment]
I could import the display settings from QuPath, that's a great idea. However, you don't need to click on every channel of every slice (I would have gone crazy).

You can set display settings for all your selected slices at once.

It's on the documentation:

https://biop.github.io/ijp-imagetoatlas/registration.html

Take care where you need to click on the gif in the `Slices display options` section

**Comment by NicoKiaru** [comment]
Note that if you save the state, you won't have to redo it this adjustement on the next opening

**Comment by Theresa-S** [comment]
Dear Nicolas,

you underestimate my laziness :-) I was setting the display setting for all slices at once, but got annoyed by having to do it for each of my four channesl individually. But I made the mistake of always loading from the QuPath project, so saving the state is a really good suggestion to avoid this.

**Comment by NicoKiaru** [comment]
Oups, ok then in this case yes, I'll try to make things easier for many channels!

**Comment by Theresa-S** [comment]
Thanks a lot and no pressure :-)

**Comment by NicoKiaru** [comment]
Ok, there will be a new command in Edit>ABBA - Set Slices Min Max Display Range in order to change the min max of many channels at once ( next release )
