### ISSUE TITLE
Atlas has to be in a path without spaces

### ISSUE THREAD

**Issue by andrewsilberfeld** [BIOP/ijp-imagetoatlas#116]
Just putting it here for future users that ABBA throws a run-time error and won't load if the path to the atlas contains a space or contains the %20 string. Therefore folder names can't have spaces in them.

Error starts with this: 
ncsa.hdf.hdf5lib.exceptions.HDF5FileNotFoundException: Path does not exit. (C:\Users\Andrew\cached%20atlas\.\ccf2017-mod65000-border-centered-mm-bc.h5)

Works: C:\Users\Andrew\cached_atlas
Does not work: C:\Users\Andrew\cached atlas

**Comment by NicoKiaru** [comment]
Thanks! Related : https://github.com/BIOP/ijp-imagetoatlas/issues/102

I need to push the new version
