### ISSUE TITLE
Subsetting the atlas?

### ISSUE THREAD

**Issue by andrewsilberfeld** [BIOP/ijp-imagetoatlas#117]
Some of my sagittal sections lost their cerebellum or olfactory tissue and it is throwing off the registration. Is there a way to subset the atlas beyond defining a region of interest? It would be super helpful if there was a way to de-select the cerebellum to remove it from the atlas or even a whole hemisphere, or similarly, if once could draw non-rectangular ROIs and register a subset of the sections to this modified atlas. 

I'm presently trying to register the more lateral sections of my sagittally cut mouse brain to a rectangular ROI atlas excluding the cerebellum, but it gives mixed results.

**Comment by NicoKiaru** [comment]
In the future there should be some support for handling masks, but that may happen in six months. The rectangular ROI is the only way currently to restrict the region used for the registration

To be fair the automated registration does not perform so well. What I hope in the near future is to get a fully functional bridge with Python where we could add other fancy registration methods.

The best way in ABBA to deal with complex registration is to go through BigWarp (or to edit a previous automated spline registration with few landmarks). Potentially you can add an automated spline registration on top of a manual ones, where you would correct the big issues first.

**Comment by andrewsilberfeld** [comment]
Thanks! The BigWarp Method has worked well. It is manual and requires work but I'm happy with the results. For me, starting with BigWarp and using only that has provided sufficient registration, and usually requires only 7-8 landmarks. I have 18-20 sections per sample and can completely register the sample in 30 minutes. I have a fair amount of samples but after a days' work, it is done.

Thanks so much for making this tool and for your responsiveness as you develop it. I'm grateful to have this tool because it plays a fundamental role in my project and does so in a way that outperforms existing tools. This is a really user-friendly tool that has allowed me to perform very careful quantification. As a non-computational biologists, this has removed the barrier for performing image registration on serial sections which now gives me objective region-specific read-outs in my data, rather than subjective guessing at where one region ends and another begins.

**Comment by NicoKiaru** [comment]
Thanks a lot for the nice comment!!
