### ISSUE TITLE
Change overlap mode

### ISSUE THREAD

**Issue by Theresa-S** [BIOP/ijp-imagetoatlas#119]
I'm not sure if this will already be different in the new version (in that case, just close my issue), but there seems to be a minor bug in the "Change overlap mode" function. 
When atlas and slides are overlaid (so like this: 
![grafik](https://user-images.githubusercontent.com/61883896/144426416-9b4d80ca-0fea-46bf-b44e-6fcd1f6f140a.png)
), "changing overlap mode" will put them immediately next to each other --> 
![grafik](https://user-images.githubusercontent.com/61883896/144426493-c277a27c-ec45-40e7-8abf-ef3ac6f18485.png)

The other way round, however, the function needs to be executed twice in order to get back to the overlay.

**Comment by NicoKiaru** [comment]
Yes, but that's because you see a difference if there are many slices next to each other - then they become organized as 'staircases'

Mode 1: 
-Atlas+Slice-Atlas+Slice-Atlas+Slice-

Mode 2: 
-Atlas-Atlas-Atlas-
-Slice-Slice-Slice-

Mode 3: 
-Atlas-Atlas-Atlas-
-Slice
        -Slice
                 -Slice-

**Comment by Theresa-S** [comment]
Ah, I didn't get that, I just noticed that nothing is happening :-D
Thanks for the clarification!
