### ISSUE TITLE
Translation Question

### ISSUE THREAD

**Issue by andrewsilberfeld** [BIOP/ijp-imagetoatlas#122]
Does translating or rotating the section prior to registration affect the results or is it purely for our visualization?

**Comment by NicoKiaru** [comment]
How do you translate or rotate ? Using the interactive transform command ?

In most cases this will affect the registration, but in a good way:  if the slices are not approximately correctly placed before automated registration, there's a chance the result won't be optimal. 

I usually stretch by 20 % the slices in y prior to automated registration.

**Comment by andrewsilberfeld** [comment]
Yes I use the interactive transform command. I see. Thank you!
