### ISSUE TITLE
angle not updated in the card UI when loading state

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/ijp-imagetoatlas#138]

**Comment by Etherian** [comment]
This bug has caused our team trouble a couple times. Do you think you could look into fixing it soon?

**Comment by NicoKiaru** [comment]
It's fixed in https://github.com/BIOP/ijp-imagetoatlas/commit/a9bdb937b9d444d2ea0728b940ec7d3a2466c39b

I can't push the fix now, but it'll be included in the next release, which should happen end of Jan next year.
