### ISSUE TITLE
Submit some modification to script installation of abba install

### ISSUE THREAD

**Issue by hedjour** [BIOP/ijp-imagetoatlas#157]
Where can we submit some modification of full_install_abba.sh ?
Thanks

**Comment by NicoKiaru** [comment]
Sure, it's on this repo: https://github.com/BIOP/biop-bash-scripts

**Comment by NicoKiaru** [comment]
FYI I've made some updates to the script. If I missed something, please open an issue in the bash scripts repo!

**Comment by hedjour** [comment]
Oki thank's I will submit you a pull request when I ending the linux support part.

**Comment by hedjour** [comment]
https://github.com/hedjour/biop-bash-scripts
I just have a problem with curl...
