### ISSUE TITLE
Data for ABBA

### ISSUE THREAD

**Issue by portarttart** [BIOP/ijp-imagetoatlas#168]
Hello,

I have been trying to use a coronal section saved as tiff file that has a green, red, and dapi fluorescence on ABBA.
However, whenever I opened the section on ABBA, I only get one channel and when I try to click the eye the entire screen goes white.
I am not sure how my data should be saved and whether I need to use a grayscale or something along those lines.

Thank you

**Comment by NicoKiaru** [comment]
By default, the min max display settings is set from 0 to 256. Try to change the max to something like 16000 and see if it gets better.

Have a look at this part of the documentation: https://biop.github.io/ijp-imagetoatlas/registration.html#slices-display-options

**Comment by portarttart** [comment]
Hi, thanks for your response and it did end up working. 
However, when I was able to visualize the image it was way too large and no matter what transformations I was able to make on the software I was not able to have it in a similar format to how it was in the yt video tutorial.
I have attached what I am seeing on the ABBA software.
![Attempt ABBA](https://github.com/BIOP/ijp-imagetoatlas/assets/134231579/fe4347a2-6a98-4ddb-9b5d-5185d586a237)

**Comment by NicoKiaru** [comment]
Hi @portarttart, are you using QuPath ? Did you set the correct pixel size in QuPath before import the project in ABBA ?

**Comment by NicoKiaru** [comment]
See also the first response of the documentation FAQ:

https://biop.github.io/ijp-imagetoatlas/#the-sections-are-gigantic-when-opened-in-abba

**Comment by NicoKiaru** [comment]
@portarttart there was a bug introduced a while ago that prevented the override of the pixel size by QuPath. In the upcoming release (any version stricltly above 0.7.4), this should bee fixed and you'll be able to override the pixel size from the QuPath project
