### ISSUE TITLE
Split the behavior of saving and loading *_bdv_view.json files into their own methods

### ISSUE THREAD

**Issue by Etherian** [BIOP/ijp-imagetoatlas#169]
I am trying to automate portions of our ABBA workflow using [abba_python](https://github.com/BIOP/abba_python). Part of that automation requires saving the view state of the BDV, i.e. the *_bdv_view.json file that is written when saving via the GUI. Unfortunately, the logic for writing this file appears to be in the [`ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView.saveState`](https://github.com/BIOP/ijp-imagetoatlas/blob/29fbc21d212008713b54297fded776ba621e99c5/src/main/java/ch/epfl/biop/atlas/aligner/gui/bdv/BdvMultislicePositionerView.java#L934) method, which ties writing the view state file to prompting the user and writing the *.abba state file.

Could the logic for saving *_bdv_view.json files be split into its own method, so that I can access the behavior via abba_python? Or, even better for my purposes, could [`ch.epfl.biop.atlas.aligner.command.ABBAStateSaveCommand`](https://github.com/BIOP/ijp-imagetoatlas/blob/b27f31f1774858aaa1303de1f1022d0228b307c7/src/main/java/ch/epfl/biop/atlas/aligner/command/ABBAStateSaveCommand.java#L15) and the [`ABBA.save_state`](https://github.com/BIOP/abba_python/blob/fdccae3d27ac75c2a5026d4e9df5df0107311d64/src/abba_python/abba.py#L569) method in abba_python be expanded to include an option to save the *_bdv_view.json file alongside the *.abba file? Along with updating the equivalent state loading functions/methods of course.

Alternatively, *_bdv_view.json could be stored in the *.abba zip archive with the rest of the state information.

**Comment by Etherian** [comment]
(To navigate the abba_python and ABBA projects, I have been using Github's search and symbol navigator features. Yeah, it's been a pain.)

I like your solution of adding a `File state_file` parameter to the `saveState` method. That solves my problem.

For context: We use ABBA for two manual steps: manual z-position adjustment and BigWarp. I am trying to automate every action but those two. My trouble is that I would like to automate setting good slice display settings for the user, min/max brightness in particular, and those settings are stored in the bdv_view file.

**Comment by NicoKiaru** [comment]
Ok, I've added the parameter, and pushed a new version. To test it, you need to change this line in your local install:

https://github.com/BIOP/abba_python/blob/01e0cefde1846508936353076d16b08bcec01325/src/abba_python/abba.py#L73
to

`abba_dep = 'ch.epfl.biop:ImageToAtlasRegister:0.5.6'`

DIsclaimer: I've not tested it, so please report back how it goes.

**Comment by NicoKiaru** [comment]
Any version above 0.5.6 should work. Closing. Please re-open if needed
