### ISSUE TITLE
Neuropixels probe tract registration

### ISSUE THREAD

**Issue by AthiemoneZero** [BIOP/ijp-imagetoatlas#170]
Hi, ABBA is really an amazing package I've ever used for mouse brain sections registration, really appreciate it!

As a newer to ABBA, I want to leverage this powerful tool to check neuropixels tract which is painted in fluorescent dye and marked by cell detection function in Qupath. I'd like to know can we calculate the central 3D position of the tract using every detected 'cell' location? So that we can export this 'regressive'  tract to AP_histology package (https://github.com/petersaj/AP_histology) or IBLapps atlaseletrocphysiology (https://github.com/int-brain-lab/iblapps/wiki) and so on to help check the real spatial location of probe sites.

**Comment by NicoKiaru** [comment]
Hi! Thanks for the kind words.

So yes it's possible to calculate the coordinates of the registered image into the atlas.

It can be done in groovy within QuPath:
- https://biop.github.io/ijp-imagetoatlas/qupath_analysis.html#importing-abba-registration-results--adding-atlas-coordinates-to-qupath-detections-measurements

It can be done with [abba_python](https://github.com/BIOP/abba_python) within a [notebook](https://github.com/BIOP/abba_python/blob/main/example_notebooks/3.%20Open%20State%20and%20Use%20Transforms.ipynb)

You will still need to 'connect the dots' between the different sections

**Comment by NicoKiaru** [comment]
Yep, I'm less expert on the python side, do not hesitate to post an issue in the other repo.
