### ISSUE TITLE
Copy registration sequence from one slice and apply it to others

### ISSUE THREAD

**Issue by penguingiraffe2** [BIOP/ijp-imagetoatlas#174]
Hello! This tool is amazing thank you so much ! 

In addition to warping the atlas and overlaying the warped atlas onto our images in qupath, i'd like to warp some of the heatmaps that qupath generates so that i can eventually make "average" heatmaps across sections from various brains for various stains. 

I can export the heatmaps as TIFF files... is there an easy way to use the registration function that ABBA generates and apply it to other images, such as the heatmap TIFF? I feel as though this would be a better method than backward transforming all the actual images and regenerating the heatmaps from the warped images. Thanks so much.

**Comment by penguingiraffe2** [comment]
just realized a nifty workaround is to save the heatmap as an additional channel in FIJI and then simply run through the standard pipeline. I'll close the question but leave this up for other folks to see. Also, in case you have better recommendations for how to go about doing this.

**Comment by NicoKiaru** [comment]
I think it should be possible to warp the image using the transformation provided by ABBA. I reopen the issue (not a priority though).

**Comment by NicoKiaru** [comment]
In the upcoming release, there will be a way to copy the registration sequence from one slice to other ones:

![image](https://github.com/BIOP/ijp-imagetoatlas/assets/20223054/5f990d51-039e-404d-87eb-43c55084e7c6)


see commit 01bbe19a909afe

**Comment by NicoKiaru** [comment]
Documentation done in https://github.com/BIOP/ijp-imagetoatlas/commit/bf53bed7b21484f8bd85b079362780db4e999636
