### ISSUE TITLE
Position of atlas acronyms decoupled from atlas borders

### ISSUE THREAD

**Issue by bgbeekly** [BIOP/ijp-imagetoatlas#176]
Hi, thanks in advance for your patience, especially if this has already been addressed and I was unable to find it. I'm brand new to using ABBA and not especially tech-savvy. 

I'm finding that the registration of my images to the atlas works well, as does importing the registrations into QuPath, but when I toggle the atlas acronyms on and off, the labels appear in one vertical line down the center of the image rather than over the brain region they correspond to (image below). It's worth noting that the images I used first came from a brain that was sectioned in a plane quite far from perpendicular to the midline, so I had to make a significant y-adjustment to the angle of the atlas--not sure if this could have anything to do with it.

![image](https://github.com/BIOP/ijp-imagetoatlas/assets/147099681/ad62ac0e-d2bb-4d7f-b94b-da9d2d52fa4c)

Is anyone else experiencing this/is there a fix I'm missing? thank you!!

**Comment by NicoKiaru** [comment]
No problem. Yes this 'weird' display comes from the fact that all regions are symmetric between left and right and the label is displayed of the 'center of mass' of each region. Thus they all end up at the center of the slice (so most of them are displayed completely outside of their region. If you split between left and right region during import, you will see a more pleasant display of these regions.  Note that the label position being weirdly displayed do not affect the downstream analysis in any way.

**Comment by bgbeekly** [comment]
> No problem. Yes this 'weird' display comes from the fact that all regions are symmetric between left and right and the label is displayed of the 'center of mass' of each region. Thus they all end up at the center of the slice (so most of them are displayed completely outside of their region. If you split between left and right region during import, you will see a more pleasant display of these regions. Note that the label position being weirdly displayed do not affect the downstream analysis in any way.


Ahh, got it - thank you so much!
