### ISSUE TITLE
Registration history and editability

### ISSUE THREAD

**Issue by bmi-lsym** [BIOP/ijp-imagetoatlas#179]
Hi Nicolas,

I think there might be an issue with the ABBA (Snapshot 0.7.4): when performing registrations, transforms are actually done, but the viewer does not show a stack of green dots for each slice as it was done in earlier versions. Accordingly, it is not possible in 0.7.4 to edit the last registration. If the project is opened with an older version (0.5.3), the same is seen: no stacks of green dots, and no possibility to edit the last one. However, if registration was done with an older version (0.5.3), then 0.7.4  reads the .abba file properly and allows editing the last registration made in 0.5.3. For an info, the version 0.6.1, which one of my colleagues is using, works well.

Thanks,
Olexiy.

**Comment by bmi-lsym** [comment]
P.S. this is specific to Elastix registrations, BigWarp seems to work and is then editable

**Comment by NicoKiaru** [comment]
Dude! Already on 0.7.4 :-). Are you running it within an IDE ? Is this an urgent problem ? I have a bunch of things to do before going on vacation, which mean I can take care of this in ~ 2 weeks.

**Comment by bmi-lsym** [comment]
Hi! Sorry, the issue is not urgent at all since the older version works perfectly fine. This was just to warn about it. Do not worry, and thanks a lot! I got 0.7.4 automatically from the FIJI update, did not download anything separately.

**Comment by NicoKiaru** [comment]
> I got 0.7.4 automatically from the FIJI update

Ah! Then it's an issue, it means it's potentially broken for everybody. I'll check

**Comment by NicoKiaru** [comment]
Hi @bmi-lsym , 

I think I've fixed the issue in Fiji, let me know if that works again.

Cheers, 

Nicolas

**Comment by bmi-lsym** [comment]
Hi Nicolas, 

Thank you very much for rapid fixing, it works now after the update!
Nice vacations!

Olexiy.
