### ISSUE TITLE
Allen Brain Adult Mouse Brain CCF 2017 invalid URLs

### ISSUE THREAD

**Issue by bpavie** [BIOP/ijp-imagetoatlas#2]
Dear,

First of all, thanks for having released the ImageJ plugin, it looks very interesting.

I wanted to test it and after having compile it, I realized that the following default URL are not working anymore:
MapURL : http://ec2-18-222-96-84.us-east-2.compute.amazonaws.com:8081/ccf_2017/
OntologyURL : http://ec2-18-222-96-84.us-east-2.compute.amazonaws.com/1.json

They are used in to pick up the Allen Brain Adult Mouse Brain CCF 2017
![image](https://user-images.githubusercontent.com/1775952/94796117-9b6a7380-03de-11eb-8f82-6a2b3f152590.png)

I think that the OntologyURL could also be downloaded from the URL http://api.brain-map.org/api/v2/structure_graph_download/1.json but I don't understand to which dataset MapURL is pointing to, would it be possible to have some information on that?

Best,
Benjamin

**Comment by NicoKiaru** [comment]
Hi Benjamin, 

You're very motivated! Just FYI, the version on the master branch is kind of working but will be removed in favor fo the one present in the sourceandconverter branch, which is WIP.

For the master branch, I removed some restriction on the document desribing the plugin, you will find the missing files in the document below:

https://docs.google.com/presentation/d/1Srw5il1AKx48oTXhBugrkILaeB4QOduIZUNneSA8g7I

I tried before to put the files before on an AWS instance, but it's better to have a atlas locally (xml/hdf5 files).

**Comment by NicoKiaru** [comment]
A bit more info here : https://docs.google.com/document/d/15s1c5V_ukGuuqjawp4XqlzxxQhnZZpILipDo5C4WwC0

But as mentioned before, it's pretty obsolete

**Comment by bpavie** [comment]
Hi Nicolas,

Actually, I cloned the branch `sourceandconverter`  and compiled it (I had some minor problems because all the depdendencies are marked as SNAPSHOT and maven returned an error `Rule 9: org.scijava.maven.plugin.enforcer.RequireReproducibleBuilds failed with message:   The following artifacts either - are SNAPSHOT versions (V), contain  SNAPSHOT parents (P), or contain SNAPSHOT dependencies (D): ` but that's another story) .

With this version, I have actually another problem in the class SacMultiSacsPositionerCommand.java, MultiSlicePositioner.java becasue the call to the method getCardPanel() is not found although the method is present in the BdHandle class from bigdataviewer-vistools (https://github.com/bigdataviewer/bigdataviewer-vistools/blob/master/src/main/java/bdv/util/BdvHandle.java ) but I noticed in your code you look to have a similar issue, so right now I commented all the lines with the call `getCardPanel()` and `bdvh.getViewerPanel()`

A last things, you use the groovy-all library in your code but it's not on the dependency in the `pom.xml`, so I added it:
```
<dependency>
	<groupId>org.codehaus.groovy</groupId>
	<artifactId>groovy-all</artifactId>
	<version>2.5.13</version>
	<type>pom</type>
</dependency>
```

Thanks for your quick answer and for sharing the code!

Benjamin


> 
> 
> Hi Benjamin,
> 
> You're very motivated! Just FYI, the version on the master branch is kind of working but will be removed in favor fo the one present in the sourceandconverter branch, which is WIP.
> 
> For the master branch, I removed some restriction on the document desribing the plugin, you will find the missing files in the document below:
> 
> https://docs.google.com/presentation/d/1Srw5il1AKx48oTXhBugrkILaeB4QOduIZUNneSA8g7I
> 
> I tried before to put the files before on an AWS instance, but it's better to have a atlas locally (xml/hdf5 files).

**Comment by NicoKiaru** [comment]
Ok, whoa!

The getCardPanel() command had an issue which is since then resolved, but not pushed, I'll push the current version later today so you can test it. That may also require recompiling bigdataviewer-playground, bigdataviewer-bioformats and bigdataviewer-biop-tools

**Comment by bpavie** [comment]
Thanks a lot!
Do you have any advice on the maven error `Rule 9: org.scijava.maven.plugin.enforcer.RequireReproducibleBuilds failed with message: The following artifacts either - are SNAPSHOT versions (V), contain SNAPSHOT parents (P), or contain SNAPSHOT dependencies (D)` due to the SNAPSHOT label ? I renamed the version to remove the SNAPSHOT on all the dependencies maven projects  (e.g. for `bigdataviewer-selector`, I renamed the version from `0.1.5-SNAPSHOT` to `0.1.5`) but I am sure there is another way that I don't know ;-)

**Comment by NicoKiaru** [comment]
You can set the flag `-Denforcer.skip = true` when running mvn.

`mvn clean install -Denforcer.skip = true`, but you may have other errors, because you need to compile these SNAPSHOT dependencies. Basically it's the current github state of these repositories. They are all developed together so that's why they are in SNAPSHOT state.

See https://github.com/NicoKiaru/bigdataviewer-selector/blob/master/pom.xml for instance.

If you want to compile a SNAPSHOT repo which depend on a SNAPSHOT repo, you can do it by removing the enforcer

**Comment by bpavie** [comment]
Ok, thanks, I will wait for the update.
For the record, I run Plugins>BIOP>Atlas>Allen Brain Adult Mouse Brain CCF 2017 and I enter for example:
MapURL : `file:/c:/mysuer/Allen_Brain_Atlas/ccf2017-mod65000.xml`
OntologyURL : `file:/c:/mysuer/Allen_Brain_Atlas/1.json`

**Comment by NicoKiaru** [comment]
This should work, yes.

I just updated the snapshot branches of all dependencies. Compiling in this order:

`ijl-utilities-wrappers`
`bigdataviewer-selector`
`bigdataviewer-playground`
`bigdataviewer-bioformats`
`bigdataviewer-biop-tools`

pfou... then finally this repo, should work.

**Comment by bpavie** [comment]
Thanks Nicolas,

I'have done update but once installed, I still have the following error when I do:
 I run Plugins>BIOP>Atlas>Allen Brain Adult Mouse Brain CCF 2017
Using the parrmeters:
MapURL : `file:/c:/mysuer/Allen_Brain_Atlas/ccf2017-mod65000.xml`
OntologyURL : `file:/c:/mysuer/Allen_Brain_Atlas/1.json`

```
Dragging support enabled
BdvHandlePostprocessor:BdvHandle found.
[ERROR] Module threw exception
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at ch.epfl.biop.atlas.allen.AllenMap.show(AllenMap.java:86)
	at ch.epfl.biop.atlas.allen.adultmousebrain.AllenBrainAdultMouseAtlasCCF2017.run(AllenBrainAdultMouseAtlasCCF2017.java:72)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

When I start Fiji now the the BDV Sources popup
The BDV panel popup when I run Plugins>BIOP>Atlas>Allen Brain Adult Mouse Brain CCF 2017 but nothing appear in it.

![image](https://user-images.githubusercontent.com/1775952/94936162-2ecea200-04ce-11eb-8ece-3bb914c801ad.png)

Benjamin

**Comment by NicoKiaru** [comment]
Right! I reallized I modified the dataset, I'll update with the new one and provide a link soon

**Comment by bpavie** [comment]
ok thanks ;-)

**Comment by NicoKiaru** [comment]
Here you go :

https://drive.google.com/file/d/16tg0MRiwA5AmBpQowRe9oXDiCJwlxDe1/view?usp=sharing

**Comment by NicoKiaru** [comment]
@bpavie the plugin can be installed by enabling the update site https://biop.epfl.ch/Fiji-ABBA

It's in decent shape, and the documentation has been started here : https://c4science.ch/w/bioimaging_and_optics_platform_biop/image-processing/image-to-atlas-registration/

I'll make a real release hopefully by the end of this month, and will announce it on forum.image.sc.

I close this issue for the moment.
