### ISSUE TITLE
Import from Qupath but obtain solid color slices

### ISSUE THREAD

**Issue by hongjie-wang-2024** [BIOP/ijp-imagetoatlas#218]
Import from Qupath to obtain solid color slices。
I imported slices from Qupath and encountered this error for each image halfway through:
Could not access omeMeta.getPlanePosition serie 0
After importing, it was found that all the slices displayed in the image were solid colors.
![image](https://github.com/user-attachments/assets/05725551-783d-406c-a1fa-0d44d9606b25)
Can anyone help me？
Thanks!

**Comment by NicoKiaru** [comment]
You need to set a max display value way above 255. Please see:

https://abba-documentation.readthedocs.io/en/latest/tutorial/2_registration.html#displaying-specific-channels

to see how to do it

**Comment by hongjie-wang-2024** [comment]
> You need to set a max display value way above 255. Please see:
> 
> https://abba-documentation.readthedocs.io/en/latest/tutorial/2_registration.html#displaying-specific-channels
> 
> to see how to do it

I have already resolved it, thank you very much!
