### ISSUE TITLE
Editing registration after BigWarp leads to frozen FIJI

### ISSUE THREAD

**Issue by bmi-lsym** [BIOP/ijp-imagetoatlas#221]
Hi Nicolas,

Thank you very much for your great work leading to continuous improvements of ABBA!

However, I think there is a possible issue after (one of) the last FIJI update. 

Namely, if I do the BigWarp manual registration of a slice to the atlas, accept it by "t" and OK button, it is fine. But if then I want to edit this registration later (in the same session of after ABBA/FIJI restart and re-loading the state), ABBA BDV and the whole FIJI lethally freezes, with 0% CPU workload. It also shows the message at the bottom of the BDV window: "Edit registration | Edition will begin when the manual lock is acquired". And then it is dead.
 
Other types of registrations, like elastix spline, are editable ok.

I have bigdataviewer* jars dated either 4th or 31st of October 2024.

Since in my case I need to do BigWarp with follow-up adjustments rather frequently, it would be great to get a fix, or a possibility to roll back to previous version until it is fixed.

Thank you very much in advance!

Olexiy.

**Comment by NicoKiaru** [comment]
Hi Olexiy, thanks for the report, I'll check if I can reproduce

**Comment by NicoKiaru** [comment]
Yes I can - great! (in a way)

**Comment by NicoKiaru** [comment]
@bmi-lsym I've just uploaded the fix to Fiji, if you update the bigwarp edition should work now.

**Comment by bmi-lsym** [comment]
I confirm it works now, thanks a lot!

**Comment by NicoKiaru** [comment]
Thanks for the very clear bug report!
