### ISSUE TITLE
[Edit > rotate] crops the slice instead of rotating it

### ISSUE THREAD

**Issue by lukasvandenheuvel** [BIOP/ijp-imagetoatlas#65]
There seems to be a problem with the command to rotate a slice (edit > rotate). On MacOS Big Sur, the image gets cropped instead of rotated (see attached screenshot).

Thank you in advance! 

<img width="1680" alt="Schermafbeelding 2021-05-24 om 18 08 11" src="https://user-images.githubusercontent.com/55539564/119375571-42c44f80-bcbb-11eb-952a-4b43caceac2b.png">

**Comment by NicoKiaru** [comment]
Hum, weird, did you select rotation around Z axis ? If you select X or Y, you have observe such 'crop'

**Comment by lukasvandenheuvel** [comment]
You're right, I though I tried all three axes but apparently not.  Thanks for the quick responses!

**Comment by NicoKiaru** [comment]
I swapped the choices, so that the default one will be Z, which is anyway the most useful one!
