### ISSUE TITLE
Moving a landmark in BigWarp does not update the displayed moving image

### ISSUE THREAD

**Issue by lukasvandenheuvel** [BIOP/ijp-imagetoatlas#66]
This problem occurs when I launch BigWarp via [align > BigWarp registration] and add a landmark with ctrl+click. Moving the landmark does not alter the moving image, which makes it hard to do the alignment. Only when I click "OK" after moving the landmark, the registration is shown.

This problem does not occur when BigWarp is launched with [align > Edit last registration].

**Comment by NicoKiaru** [comment]
Try to press 't' for 'transform in BigWarp. This computes the transformation live. This mode is set up by default when editing the registration, but not in BigWarp. The problem is that it can't be activated by default if there's no landmark...

**Comment by lukasvandenheuvel** [comment]
Yes this works perfectly, I was confused because it was activated by default when editing the registration. Thank you!

**Comment by NicoKiaru** [comment]
Yes, I can add a warning message.

FYI, I also updated the documentation, which should be more or less ok (with typos, etc.)

https://biop.github.io/ijp-imagetoatlas/

There's the part with BigWarp : https://biop.github.io/ijp-imagetoatlas/registration.html#bigwarp-registration-manual

**Comment by NicoKiaru** [comment]
I added a small message in the "closing" window
