### ISSUE TITLE
[Align > Edit last registration] Improve how displayed channels are chosen

### ISSUE THREAD

**Issue by lukasvandenheuvel** [BIOP/ijp-imagetoatlas#67]
When I launch BigWarp via [Align > Edit last registration], there is no possibility to choose which channels of the moving image and the Atlas image are displayed. There is the possibility to either display the first channel of both images, or the first channel on the Atlas image with all channels on the moving image ("Edit with all channels"). It would be nice to have the possibility to choose the channels, as is the case when you launch BigWarp via [Align > BigWarp registration].

**Comment by NicoKiaru** [comment]
You can activate or deactivate channel by opening the right panel (look for a blue arrow when you hover your mouse on the right):

![image](https://user-images.githubusercontent.com/20223054/119396971-d86cd880-bcd5-11eb-84b4-5b9426e6a14e.png)

But yes, I can try to make that channel selection easier

**Comment by lukasvandenheuvel** [comment]
Thank you, I hadn't tried the right panel yet.
I see this pannel now, where can I change the displayed channel?

<img width="1564" alt="Schermafbeelding 2021-05-24 om 21 28 24" src="https://user-images.githubusercontent.com/55539564/119397845-0272ca80-bcd7-11eb-8450-58fa26536886.png">

**Comment by NicoKiaru** [comment]
Ah, you need to edit with all channels, then remove the useless ones. 

FYI this looks like a lot of landmarks :-0 !

**Comment by lukasvandenheuvel** [comment]
Makes sense, now it works. Thanks for the quick responses!

**Comment by NicoKiaru** [comment]
I'll just let the issue open for the channel choice improvement
