### ISSUE TITLE
Retrieve the hierarchical tree of annotations

### ISSUE THREAD

**Issue by lukasvandenheuvel** [BIOP/ijp-imagetoatlas#72]
For the python script I'm trying to cluster brain regions according to their hierarchy, so that we can decide at all times which level of detail we want in the analysis. In QuPath I can see that the hierarchy is there:

<img width="762" alt="Schermafbeelding 2021-06-02 om 13 58 37" src="https://user-images.githubusercontent.com/55539564/120476236-a250e800-c3aa-11eb-8360-2b88a8769353.png">

I tried to retrieve the hierarchical tree from just the abbreviated names of the annotations, but it gives me an incomplete result:

[whole_brain_tree_abbs.pdf](https://github.com/BIOP/ijp-imagetoatlas/files/6584247/whole_brain_tree_abbs.pdf)

(if you zoom in on the pdf you will see the abbreviations).
We would, for example, want the nucleus reuniens (RE) to be part of the thalamus (TH), but right now they aren't because their abbreviated names are unrelated.

Is there some automated way to get the hierarchical tree from ABBA or QuPath? Just a list of edges in the tree would be enough.

Thanks!

**Comment by NicoKiaru** [comment]
Yes, it's retrieved for instance in QuPathBiop Tools at this line:

https://github.com/BIOP/qupath-biop-extensions/blob/efefe758f0fb69190f7778081b1148423f784b75/src/main/java/ch/epfl/biop/qupath/atlas/allen/api/AtlasTools.java#L99

The [AllenOntologyJson](https://github.com/BIOP/qupath-biop-extensions/blob/master/src/main/java/ch/epfl/biop/qupath/atlas/allen/AllenOntologyJson.java) object is created by deserializing the [mouse allen brain ontology json file](http://api.brain-map.org/api/v2/structure_graph_download/1.json).

In this object, there's a field called [`msg`](https://github.com/BIOP/qupath-biop-extensions/blob/efefe758f0fb69190f7778081b1148423f784b75/src/main/java/ch/epfl/biop/qupath/atlas/allen/AllenOntologyJson.java#L16) which is a list of `AllenBrainRegion`. In each of the `AllenBrainRegion` you have [children `AllenBrainRegion`](https://github.com/BIOP/qupath-biop-extensions/blob/efefe758f0fb69190f7778081b1148423f784b75/src/main/java/ch/epfl/biop/qupath/atlas/allen/AllenOntologyJson.java#L29), and thus you get the whole hierarchy.

**Comment by lukasvandenheuvel** [comment]
Fantastic, this worked! I hadn't realized that the information was in the json file all the time.
The actual tree turns out to be much harder to plot on the screen...

[whole_brain_tree_abbs.pdf](https://github.com/BIOP/ijp-imagetoatlas/files/6587659/whole_brain_tree_abbs.pdf)

Anyway, thanks again!
