### ISSUE TITLE
Work with other atlases

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/ijp-imagetoatlas#74]
Rather long term than very long term

**Comment by NicoKiaru** [comment]
Some progress done - the ugly atlas interface has been replaced by a much less ugly one. Still there are some hardcoded parameters here and there

**Comment by NicoKiaru** [comment]
Works now. For example a rat atlas is available

**Comment by NicoKiaru** [comment]
QuPath extension needs to work with it however

**Comment by NicoKiaru** [comment]
Ah! Are these atlases public or is it some of your data ?
What is the format of the image data and of the ontology ?

The next release will support the atlases in brainglobe https://github.com/brainglobe/bg-atlasapi, and this rat atlas:https://www.nitrc.org/projects/whs-sd-atlas

**Comment by andrewsilberfeld** [comment]
Public atlas from this link: http://repo.mouseimaging.ca/repo/Embryo_Atlas_CT_E15.5_nifti/
-- "final.model.nii" is the popuation-averaged z-stack 
-- segmented structures is "Embryo_Atlas_labels.nii"
-- pdf key for name of structure according to pixel values in segmented image: http://www.mouseimaging.ca/mnc/mouse_embryo_atlas/Embryo_Labels.pdf

Documentation: http://www.mouseimaging.ca/technologies/mouse_atlas/mouse_embryo_atlas.html

There are others but this would be my starting point.

**Comment by NicoKiaru** [comment]
For the ebrains atlas, I can't open the files. It does not seem to be supported by bio-formats (https://docs.openmicroscopy.org/bio-formats/6.8.0/supported-formats.html)

For the nifty files, do you think it would be ok if I repackage the atlas into a different format, and make it accessible via zenodo ? The nifty files open with float typed pixels, and I support integers only (8, 16, 32bits, signed and unsigned, but apparently it's not enough :-< ) - so directly opening nifty files requires a bit of extra work...

Of course I would acknowledge the original authors and paper of the atlas. I did this for the other atlases (for instance https://zenodo.org/record/5644162#.Ybutnlko_iE  ). In the plugin, I put the doi and link to the original atlas paper - the zenodo repo is "transparent".

If you know who I should contact to do that, please tell me, or maybe contact them directly.

I've also asked if there are some mouse embryo atlases in brainglobe (https://github.com/brainglobe/bg-atlasapi). ABBA will support brainglobe atlas api - but the usage will require a bit of python installation.

**Comment by yoda-vid** [comment]
Hi @NicoKiaru, for the ebrains atlas in MetaImage format, I can open it with Fiji or SimpleITK (passing in the `.mhd` file). I can also export it to other formats if you need. I know that @pr4deepr is working on integrating it into the BrainGlobe API (https://github.com/brainglobe/bg-atlasgen/pull/11).

**Comment by NicoKiaru** [comment]
Thanks @yoda-vid! Yes I noticed it was opening in Fiji, but I'm not sure it opens through Bio-Formats, maybe with another library. ABBA uses bio-formats exclusively. Good to know that it'll be in brainglobe!

**Comment by andrewsilberfeld** [comment]
Thanks! I only know the original paper: Wong, M. D., Dorr, A. E., Walls, J. R., Lerch, J. P., & Henkelman, R. M. (2012). A novel 3D mouse embryo atlas based on micro-CT. Development, 139, 3248–3256. doi:10.1242/dev.082016

I've never spoken with the authors previously and don't know them personally. I imagine repackaging it would be OK with proper citation but I don't have experience in this area and it's probably best to ask them directly.

**Comment by pr4deepr** [comment]
I only generated two of them mouse e11_5 and mouse e15_5. Perhaps you can have a look at them here?
https://cloudstor.aarnet.edu.au/plus/s/nukJ5DmdxxXWXtj

I used code from this pull request. Although I haven't worked on it for a bit:
https://github.com/brainglobe/bg-atlasgen/pull/11

**Comment by pr4deepr** [comment]
No, they haven't been implemented in brainglobe as far as I know.

**Comment by yoda-vid** [comment]
@pr4deepr I hadn't realized you had built a GUI for atlas generation in BrainGlobe! The screenshots look beautiful.

To get the atlases into BrainGlobe, would it be helpful for me to work on this? I haven't been too involved with BG but can build off of your scripts and see how we can integrate them. @NicoKiaru would that be helpful for your plugin?

**Comment by pr4deepr** [comment]
@yoda-vid 
I've updated the code for the gui to work now. I've only tested it on Linux and on Python 3.9
https://github.com/pr4deepr/bg-atlasgen
However, I am getting a _"tuple out of index error"_ during the atlas generation process.. I'm not sure I'll be able to troubleshoot, but @ada

You'll have to select "`mouse_e_15_5`" under Atlas generation script. However, this should work with most atlases in your paper. Only thing is that you'll have to change the download link, which is the "Download Dataset" link in the ebrains website. 

To run without gui, you can run the script, `mouse_e_15_5.py `within the `atlas_scripts` directory. The parameters are specified in the function `create_atlas`.. 

Recent updated doc about adding atlases: https://docs.brainglobe.info/bg-atlasapi/adding-a-new-atlas

**Comment by yoda-vid** [comment]
Thanks, @pr4deepr, this looks great! I set up the GUI from your fork, and it's working smoothly so far. The `tuple out of index error` apparently is from a couple additional parameters added to the mesh creation (decimation factor and smoothing), which I was able to fix by using values from other the other atlas scripts. Looks like this will generate the atlas smoothly for BrainGlobe, and I can test it on the other developing atlases as well. Hope this will help @NicoKiaru's work too.

I'll carry on the discussion of your GUI in the BrainGlobe issue you mentioned.

**Comment by adamltyson** [comment]
Hi all, just wanted to chime in and say I'm very happy to help where possible to bring more atlases into BrainGlobe, and ideally into the ABBA/FIJI world where possible. 

@NicoKiaru although our API is written in Python, the atlases themselves are packaged up in a language-agnostic manner. Is there any value in developing a Java version of the BrainGlobe Atlas API, or is always going to be easier to interact with them via Python?

**Comment by NicoKiaru** [comment]
> @NicoKiaru although our API is written in Python, the atlases themselves are packaged up in a language-agnostic manner. Is there any value in developing a Java version of the BrainGlobe Atlas API, or is always going to be easier to interact with them via Python?

Well, having a Java version avoids some installation hassle for end users. So... yes, I think there would be some value to it.
However going the extra step and using python also brings deep learning models such as DeepSlice and potentially fancy registration methods. So personally I won't put work into a Java version and concentrate on the python bridge. If other people are interested in having a direct Java brige, I'm willing to help, the ideal location for this direct bridge (and for me) would be in https://github.com/BIOP/ijp-atlas

**Comment by NicoKiaru** [comment]
The way to work with other atlases is through python with ABBA Python:

https://github.com/NicoKiaru/ABBA-Python

I'm keeping the issue open because I need to add some documentation to it

**Comment by NicoKiaru** [comment]
This has been added to the documentation
