### ISSUE TITLE
Rotate slices with a slider

### ISSUE THREAD

**Issue by lukasvandenheuvel** [BIOP/ijp-imagetoatlas#81]
Hi Nico,
I'm spending quite some time on rotating the slices, since the alignment results are much better if the slices are rotated to an upright position.
It would be very convenient to rotate the slices with a slider instead of with the current [Edit > rotate] option where you first need to 'guess' a rotation angle.

This is just a suggestion for enhancement, to make the pre-processing less time consuming.
Thanks!

**Comment by NicoKiaru** [comment]
Right! Thanks for the suggestions. I'll try to implement it. For now you can also use a BigWarp registration and press F2 to force a more rigid deformation

**Comment by NicoKiaru** [comment]
Done in https://github.com/BIOP/ijp-imagetoatlas/commit/12ec36e02dd453830a6ce420f01d7cd6378b4700 and https://github.com/BIOP/ijp-imagetoatlas/commit/51a8dea19cfaf3d8545291ff88da574b2384f082
