### ISSUE TITLE
Alignments are skipped

### ISSUE THREAD

**Issue by lukasvandenheuvel** [BIOP/ijp-imagetoatlas#82]
Hi,
When I do an alignment (either affine or spline) on the server parallel on many slices, some of the slices are skipped (see screenshot).
<img width="365" alt="Schermafbeelding 2021-07-03 om 18 31 46" src="https://user-images.githubusercontent.com/55539564/124361107-aaac7500-dc2d-11eb-9b0a-eaadc14f8755.png">

You can find the output of the Fiji console here:
[FijiConsole.txt](https://github.com/BIOP/ijp-imagetoatlas/files/6758724/FijiConsole.txt)

If I do the alignment again on skipped slices, it usually works without problems. Do you think it's a problem with the server?

**Comment by NicoKiaru** [comment]
Did you update Fiji? I tried to put at least an error message in a recent fix. I think I put a timeout somewhere in the client or the server which is not long enough.

**Comment by lukasvandenheuvel** [comment]
I did an update, and tried an affine alignment on 117 slices.
Roughly ~25 were succesful, the rest was skipped.

Here's the Fiji Console output:
[FijiConsole.txt](https://github.com/BIOP/ijp-imagetoatlas/files/6774991/FijiConsole.txt)

**Comment by NicoKiaru** [comment]
Ok, and without any error message in a popup window ?

**Comment by lukasvandenheuvel** [comment]
I noticed that there are some weird things added in the .txt file due to rtf->.txt conversion, I think this one is better:

[FijiConsole.txt](https://github.com/BIOP/ijp-imagetoatlas/files/6774997/FijiConsole.txt)

Indeed, I don't get any pop-up windows.

**Comment by lukasvandenheuvel** [comment]
Did the update also change the way in which states are imported/exported? When I import alignments I did previously, they look quite deformed.

![Schermafbeelding 2021-07-07 om 09 10 54](https://user-images.githubusercontent.com/55539564/124715374-3ca0d000-df03-11eb-8bc2-7c37128c7657.png)

**Comment by NicoKiaru** [comment]
I'll check in the history of commits when the change happened

**Comment by NicoKiaru** [comment]
should be fixed in new version
