### ISSUE TITLE
Add 'export deformation field' command in the documentation

### ISSUE THREAD

**Issue by HernandoMV** [BIOP/ijp-imagetoatlas#93]
Hi, I am not sure if this is the right place to post this but please let me know otherwise.
First of all, thanks for this, it is a fantastic piece of software! Super useful!
My question: for the slices that I want to register, I have coordinates of interest (cell positions). How do I apply to them the registrations done by ABBA in order to have them in atlas space? I could not find how to do this in the docs. Thanks,

**Comment by NicoKiaru** [comment]
Hi @HernandoMV and thanks for the message, 

This place is fine for additional features, the forum image.sc is fine as well.

Quick question: do you use QuPath ? So you want the atlas coordinates of the detected cells in QuPath ?

If that's the case, you can have a look at the last script of the documentation: https://biop.github.io/ijp-imagetoatlas/qupath_analysis.html#display-results . It appends to cell detections the coordinates of the cells in the atlas.

**Comment by HernandoMV** [comment]
I don't use QuPath, but I can use it if needed. 

What I have is a .txt file for every slice like so:
x, y
20, 50
15, 132
....

were each line are the positions (pixels or microns) for a cell of interest

What I need to get after slice registration is another .txt file for every slice (or for an animal [set of slices]) like this:
x, y, z
45, 78, 250
...

with the atlas coordinates for every cell (pixels/microns/whatever)

I don't detect the cells with QuPath, but I could try to reproduce it's output and then extract the info. Do you think that would work? Thanks!

**Comment by NicoKiaru** [comment]
Ok, maybe what you can try is this:

![image](https://user-images.githubusercontent.com/20223054/130055786-09d5cf30-3036-4acd-8f3e-e436ee32bbd5.png)

It ouputs, for each slice, a 3 channel image (float32 bits) where the channels are the x, y and z atlas coordinates (in mm) of the original pixel image.

**Comment by NicoKiaru** [comment]
Ah! You may have to update ImageJ for this to work: 

Help> Update ImageJ..., then choose `v1.53k`

Cheers, 

Nico

**Comment by HernandoMV** [comment]
Thanks Nico this is excellent and all I need. Awesome. What is the order of the channels? A->P, D->V, M->L ?
Cheers,

**Comment by NicoKiaru** [comment]
I always struggle to find this information, but here is how the CCFv3 coordinates are defined:

http://help.brain-map.org/download/attachments/5308472/3DOrientation.png?version=1&modificationDate=1368132564812&api=v2

**Comment by NicoKiaru** [comment]
@HernandoMV I'm just leaving the issue open to remind me of modifying the documentation

**Comment by NicoKiaru** [comment]
Documentation done:

See export (https://biop.github.io/ijp-imagetoatlas/export.html) and the drawing of the ccfv3 in https://biop.github.io/ijp-imagetoatlas/usage.html

**Comment by andrewsilberfeld** [comment]
@HernandoMV Do you mind sharing how you applied the deformation field to your text doc? I would like to do approach, but I can't figure out what to do once I get my deformation field. I can count cells in Ilastik, grab their positions in fiji from the binarized mask, but I want to get the positions in atlas space.

**Comment by HernandoMV** [comment]
Hi @andrewsilberfeld, when you follow the instructions that Nico shared in the previous post, you do get an image, with the same x/y size as the image you register to the atlas, but with 3 channels. The way to read that image is the following. For each pixel location in your original image (e.g. the center of a cell), the value of that same pixel location in each of the channels corresponds to one of the three coordinates in atlas space, I believe in milimeters. It works as a look-up table basically. Is this what you wanted?
Cheers,

**Comment by andrewsilberfeld** [comment]
Yes! I see now. Thank you!
