### ISSUE TITLE
Export regions to ROI manager

### ISSUE THREAD

**Issue by HernandoMV** [BIOP/ijp-imagetoatlas#94]
Hi, I am trying to export the atlas annotations on the original slices coordinates. I tried using the 'Export regions to ROI manager', but I get the following result:
![2021-08-23_13-35](https://user-images.githubusercontent.com/6049065/130448040-1ea109dc-a1df-4a48-b76a-051f342c6dc9.png)

**Comment by NicoKiaru** [comment]
Hmm, not great.

Any chance you can share your image(s) and associated xml and json files ? (You can get them by saving your 'state' file)

One note: the fact that you have pixels mentioned in the image means that something is not calibrated. This may be the cause of the issue

**Comment by HernandoMV** [comment]
Nevermind, I was being stupid and overlying them on the wrong image.... It works perfectly thank you!

**Comment by NicoKiaru** [comment]
Nice to hear that it works! Thanks for reporting
